scene.setBackgroundColor(9)
let mySprite = sprites.create(img`
    .........ccc........
    ......cccc3cc.......
    .....cc3c3c3c.......
    .....c33ccbcc.......
    .....cb3cb3b3c......
    .....ccccccc3c......
    .....c33bbc33c......
    .....cc333cccc......
    ......ccccc7..6.....
    ...........7666.....
    .......5..766.......
    .......7776.........
    ........76..........
    ........6...........
    ........6...........
    ........6...........
    ........66..........
    .........6..........
    ....................
    ....................
`, SpriteKind.Player)
game.onUpdateInterval(1000, function on_update_interval() {
    let projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . .
        . . . . . . . . . . . . . . . .
        . . . . . . . . . . . . . . . .
        . . . . . 1 1 1 1 . . . . . . .
        . . . . . . 1 1 1 . . . . . . .
        . . . . . . . 1 1 . . . . . . .
        . . . 5 a 5 a 5 a 5 a 5 5 5 . .
        . . 5 5 a 5 a 5 a 5 a 5 a 5 a .
        . . 5 5 a 5 a 5 a 5 a 5 5 5 5 .
        . . 5 5 a 5 a 5 a 5 a 5 5 a 5 .
        . . . 5 a 5 a 5 a 5 a 5 5 5 . .
        . . . . . . . . . . . . . . . .
        . . . . . . . . . . . . . . . .
        . . . . . . . . . . . . . . . .
        . . . . . . . . . . . . . . . .
        . . . . . . . . . . . . . . . .
    `, mySprite, randint(-25, 25), randint(-25, 25))
    projectile.lifespan = 3000
    if (projectile.vx < 0) {
        projectile.image.flipX()
    }
    
})
